.\" Manpage for printf
.\" Contact holberton@holbertonschool.com to correct errors or typos
.TH _printf 1 "November 2023" "Holberton Coding School 1.0" "User Commands"

.SH NAME
printf \- format and print data

.SH SYNOPSIS
.B printf
.RI "\fIFORMAT\fP [\fIARGUMENT\fP]..."

.SH DESCRIPTION
The
.B printf
command formats and prints arguments under the control of the FORMAT string. It takes one mandatory argument, FORMAT, and optionally, a series of ARGUMENTs.

.SH OPTIONS
.TP
.B FORMAT
A string that specifies the output format. It may contain plain characters and format specifiers.

.TP
.B ARGUMENT
A value to be formatted according to the FORMAT string.

.SH FORMAT SPECIFIERS
.TP
%d
Print the corresponding argument as a decimal integer.

.TP
%i
Print the corresponding argument as a decimal integer.

.TP
%u
Print the corresponding argument as an unsigned integer.

.TP
%c
Print the corresponding argument as a single character.

.TP
%s
Print the corresponding argument as a string.

.TP
%x
Print the corresponding argument as a hexadecimal integer with lowercase letters.

.TP
%X
Print the corresponding argument as a hexadecimal integer with uppercase letters.

.TP
%o
Print the corresponding argument as an octal integer.

.TP
%p
Print the memory address of the corresponding pointer argument.

.TP
%%
Print a literal '%'.

.SH EXAMPLES

.RS
.B _printf("Hello %s", "World")
.PP
Output: Hello, World!
.RE

.RS
.B _printf("The value is %d" 42)
.PP
Output: The value is 42
.RE

.SH EXIT STATUS
The
.B printf
command returns the total count of characters that were printed.

.SH SEE ALSO
printf(3)

.SH AUTHOR
Louis Toro & Antonio De Jesus.

.SH REPORTING BUGS
Report bugs to the printf package maintainer.

.SH COPYRIGHT
Copyright (C) Holberton Coding School. This is free software: you are free to change and redistribute it.
